import path from 'path';
import fs from 'fs';
import { runFfmpeg, newJobId } from './jobs.js';
import { tempDir, hashPath } from './temp.js';
import { STAGE, TIER } from '../shared/ipc.js';
import { buildThumbFilters, buildRenderArgs } from '../shared/filters.js';


/**
 * Tier 2 — container rewrite. No decode, no encode; runs at disk speed.
 */
export async function remuxProxy({ srcPath, sender }) {
  const out = path.join(tempDir(), `proxy_${hashPath(srcPath)}.mp4`);
  const jobId = newJobId();
  await runFfmpeg({
    jobId,
    stage: STAGE.REMUX,
    outPath: out,
    sender,
    args: ['-y', '-v', 'error', '-i', srcPath, '-c', 'copy', '-movflags', '+faststart',
           '-progress', 'pipe:1', '-nostats', out],
  });
  return { path: out, tier: TIER.REMUX };
}

/**
 * Tier 3 — preview transcode. Preview only: this file is never an input to the
 * final render. -hwaccel auto is safe here for the same reason, and the short
 * GOP keeps scrubbing responsive.
 */
export async function transcodeProxy({ srcPath, duration, sender }) {
  const out = path.join(tempDir(), `proxy_${hashPath(srcPath)}.mp4`);
  const jobId = newJobId();
  await runFfmpeg({
    jobId,
    stage: STAGE.TRANSCODE,
    totalSeconds: duration,
    outPath: out,
    sender,
    args: [
      '-y', '-v', 'error',
      '-hwaccel', 'auto',
      '-i', srcPath,
      '-vf', 'scale=-2:720',
      '-c:v', 'libx264', '-preset', 'veryfast', '-crf', '23',
      '-g', '24', '-keyint_min', '24', '-sc_threshold', '0',
      '-pix_fmt', 'yuv420p',
      '-c:a', 'aac', '-b:a', '128k',
      '-movflags', '+faststart',
      '-progress', 'pipe:1', '-nostats',
      out,
    ],
  });
  return { path: out, tier: TIER.TRANSCODE };
}

/**
 * Filmstrip thumbnails, generated by SEEKING rather than decoding through.
 * Cost scales with thumbnail count, not clip duration — a 40 minute clip costs
 * the same as a 2 minute one. See CLAUDE.md section 5.4.
 *
 * Tone-mapped for HDR sources so the strip matches what the player shows.
 * Failure is non-fatal to the caller: the timeline falls back to a plain track.
 */
export async function buildFilmstrip({ srcPath, duration, count, height, isHDR, rotation = 0, jobId, sender, onProgress }) {
  // Cache key covers everything that changes the pixels or the sample times:
  // rotate the video and the old thumbnails must NOT be reused.
  const dir = path.join(tempDir(), `strip_${hashPath(srcPath)}_r${rotation}_n${count}_h${height}`);
  fs.mkdirSync(dir, { recursive: true });

  const vf = buildThumbFilters({ isHDR, height, rotation });
  const results = new Array(count);
  let done = 0;
  let cancelled = false;

  const makeOne = (i) =>
    new Promise((resolve) => {
      if (cancelled) return resolve();
      // Spread samples across the clip, avoiding the very last frame which
      // some containers cannot seek to cleanly.
      const t = duration * ((i + 0.5) / count);
      const out = path.join(dir, `t${String(i).padStart(4, '0')}.jpg`);

      if (fs.existsSync(out)) {
        results[i] = out;
        done += 1;
        onProgress?.(done / count);
        return resolve();
      }

      runFfmpeg({
        jobId: `${jobId}:${i}`,
        stage: STAGE.FILMSTRIP,
        outPath: out,
        args: ['-y', '-v', 'error', '-ss', String(t), '-i', srcPath,
               '-vf', vf, '-frames:v', '1', '-q:v', '4', out],
      })
        .then(() => { results[i] = out; })
        .catch(() => { results[i] = null; })
        .finally(() => {
          done += 1;
          onProgress?.(done / count);
          resolve();
        });
    });

  // Small pool: enough to use the machine, not so many that a long strip
  // starves the render or the UI.
  const POOL = 6;
  let next = 0;
  const workers = Array.from({ length: Math.min(POOL, count) }, async () => {
    while (next < count && !cancelled) {
      const i = next;
      next += 1;
      await makeOne(i);
    }
  });
  await Promise.all(workers);

  return results.filter(Boolean);
}

/**
 * The final render. Always reads the ORIGINAL file — any code path that
 * renders from a proxy is a bug (CLAUDE.md section 5.3).
 *
 * -t not -to, because with -ss before -i the semantics of -to have changed
 * across FFmpeg versions and duration is unambiguous.
 */
export async function renderOutput({ req, jobId, sender }) {
  const args = buildRenderArgs(req);

  await runFfmpeg({
    jobId,
    stage: STAGE.RENDER,
    totalSeconds: req.duration,
    outPath: req.outPath,
    sender,
    args,
  });
  return req.outPath;
}
